CREATE TABLE COMPANY (
	ID BIGINT auto_increment PRIMARY KEY,
	NAME varchar(50) not null,
	DESCRIPTION varchar(255) not null,
	CREATIONDATE timestamp default CURRENT_TIMESTAMP,
	BELONGSTO BIGINT,
	IDLOGO BIGINT,
	LEVEL INTEGER,
	COMPANYTYPE varchar(20),
);

CREATE TABLE ACCESSORY(
	ID BIGINT auto_increment PRIMARY KEY,
	NAME varchar(50) not null,
	DESCRIPTION varchar(50),
	SERIAL varchar(50) not null,
	MODEL varchar(50),
);

CREATE TABLE BINARYFILE(
	ID BIGINT auto_increment PRIMARY KEY,
	CONTENT BLOB(56K),
);

CREATE TABLE DRIVER(
	ID varchar(50),
	NAME varchar(50) not null,
	LICENSE varchar(50) not null,
	NATIONALITY varchar(50) not null,
	constraint DRIVER_PK PRIMARY KEY (ID)
);

CREATE TABLE MANTEINANCE(
	ID BIGINT auto_increment PRIMARY KEY,
	DESCRIPTION varchar(255) not null,
	VEHICLEID BIGINT,
	STARTEDAT timestamp default CURRENT_TIMESTAMP,
	ENDEDAT timestamp,
	DURATION INTEGER,
);

CREATE TABLE URLRESOURCE(
	ID BIGINT auto_increment PRIMARY KEY,
	DESCRIPTION varchar(50),
	VEHICLEID BIGINT,
);

CREATE TABLE VEHICLE(
	ID BIGINT auto_increment PRIMARY KEY,
	BRAND varchar(50) not null,
	PLATE varchar(20) not null,
	COMPANYID BIGINT,
	BRANCHID BIGINT,
	AVAILABLE boolean default true,
);

CREATE TABLE VEHICLE_ACCESSORY(
	ID BIGINT auto_increment PRIMARY KEY,
	VEHICLEID BIGINT,
	ACCESSORYID BIGINT,
);

CREATE TABLE RENT(
	ID BIGINT auto_increment PRIMARY KEY,
	DESCRIPTION varchar(255) not null,
	VEHICLEID BIGINT,
	CREATEDAT timestamp default CURRENT_TIMESTAMP,
	UPDATEDAT timestamp,
	STATUS BOOLEAN,
	DRIVERID varchar(50),
	DURATION BIGINT NOT NULL,
);

CREATE TABLE ROL (
	ID INTEGER auto_increment PRIMARY KEY,
	NAME varchar(20) not null,
	DESCRIPTION varchar(255),
);

CREATE TABLE TRANSACTION(
	ID INTEGER auto_increment PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	PARENT INTEGER,
	TRANSACTIONTYPE varchar(20) not null,
	LEVEL INTEGER,
	URL varchar(20),
	
);

CREATE TABLE ROLES_TRANSACTION(
	ID BIGINT auto_increment PRIMARY KEY,
	TRANSACTIONID INTEGER,
	ROLID INTEGER,
);

CREATE TABLE USER (
	LOGIN VARCHAR(20) PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL,
	BIRTH DATE,
	MAIL VARCHAR(50) NOT NULL,
	POSITION VARCHAR(50),
	ROLID INTEGER,
);

CREATE TABLE USER_COMPANY(
	ID BIGINT auto_increment PRIMARY KEY,
	USERID VARCHAR(20),
	COMPANYID BIGINT,
);

--Constraints

--ALTER TABLE VEHICLE_ACCESSORY ADD CONSTRAINT VEHICLE_ACCESSORY_UK (VEHICLEID, ACCESSORYID);



insert into COMPANY (name, description) values ('rental car', 'We rent cars');
insert into COMPANY (name, description) values ('rent cheapest', 'The cheapest deal');