CREATE TABLE COMPANY (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	description varchar(255) not null,
	created timestamp default CURRENT_TIMESTAMP
);

insert into COMPANY (name, description) values ('rental car', 'We rent cars');
insert into COMPANY (name, description) values('rent cheapest', 'The cheapest deal');